"""add field activate

Revision ID: d9c181c74216
Revises: 8b12a1fe75cb
Create Date: 2026-02-16 11:28:09.449953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9c181c74216"
down_revision: Union[str, Sequence[str], None] = "8b12a1fe75cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hero", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hero", "active")
    # ### end Alembic commands ###
